packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@google/genai': false
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  protobufjs: false
  sharp: false
  unrs-resolver: false
